### ISSUE TITLE
!!Test_Suite model blocked!!

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#281] opened 2015-04-20 07:40 UTC
When opening the test_suite i get the following errors from SpeedSupervision:
Loading project Testbench_Suite.etp...  
D:/Github/modeling/model/Scade/System/ObuFunctions/SpeedSupervison/TargetManagement/extractEOASvLTargetFromMA.xscade (0): error : An exception occurred! Type:RuntimeException, Message:The primary document entity could not be opened.   Id=D:\Github\modeling\model\Scade\System\ObuFunctions\SpeedSupervison\TargetManagement\extractEOASvLTargetFromMA.xscade
D:/Github/modeling/model/Scade/System/ObuFunctions/SpeedSupervison/TargetManagement/extractLOATargetsFromMA.xscade (0): error : An exception occurred! Type:RuntimeException, Message:The primary document entity could not be opened.   Id=D:\Github\modeling\model\Scade\System\ObuFunctions\SpeedSupervison\TargetManagement\extractLOATargetsFromMA.xscade
D:/Github/modeling/model/Scade/System/ObuFunctions/SpeedSupervison/TargetManagement/extractLOATargetsFromMAint.xscade (0): error : An exception occurred! Type:RuntimeException, Message:The primary document entity could not be opened.   Id=D:\Github\modeling\model\Scade\System\ObuFunctions\SpeedSupervison\TargetManagement\extractLOATargetsFromMAint.xscade
D:/Github/modeling/model/Scade/System/ObuFunctions/SpeedSupervison/TargetManagement/extractLOATargetsFromMAint.xscade (0): error : An exception occurred! Type:RuntimeException, Message:The primary document entity could not be opened. Id=D:\Github\modeling\model\Scade\System\ObuFunctions\SpeedSupervison\TargetManagement\extractLOATargetsFromMAint.xscade
D:/Github/modeling/model/Scade/System/ObuFunctions/SpeedSupervison/TargetManagement/extractLOATargetsFromMA.xscade (0): error : An exception occurred! Type:RuntimeException, Message:The primary document entity could not be opened. Id=D:\Github\modeling\model\Scade\System\ObuFunctions\SpeedSupervison\TargetManagement\extractLOATargetsFromMA.xscade
D:/Github/modeling/model/Scade/System/ObuFunctions/SpeedSupervison/TargetManagement/extractEOASvLTargetFromMA.xscade (0): error : An exception occurred! Type:RuntimeException, Message:The primary document entity could not be opened. Id=D:\Github\modeling\model\Scade\System\ObuFunctions\SpeedSupervison\TargetManagement\extractEOASvLTargetFromMA.xscade
(0) : error ERRSEM_TYPE_NOT_DEC : _L7 : Common_Types_Pkg::Packets_T, The type Common_Types_Pkg::Packets_T is not declared

Can you please provide the corrections asap.

@BenjaminBeichler

**Comment by BenjaminBeichler** [comment] 2015-04-20 10:46
I think it is a problem of read/write permissions, but I'm not able to
check this.

Bernd Hekele <notifications@github.com> schrieb am Mo., 20. Apr. 2015 09:40:

**Comment by T12z** [comment] 2015-04-20 11:50
This is most probably caused by Benjamin's last commit, either missing git-add of referenced files (extractEOASvLTargetFromMA.xscade, extractLOATargetsFromMA.xscade, extractLOATargetsFromMAint.xscade) or a commit-before-save-bug where the etp-file is out of sync. Either way, I cannot help with a few clicks.
As Benjamin is out of office today without the Scade-Laptop it may not be fixable today. We'll see if I may be able to provide something a little later, if Benjamin is available via :phone: for a fix-over-voice.
Sorry for that!

**Comment by BenjaminBeichler** [comment] 2015-04-21 07:59
fixed by 5585dffb8a7f351c3c9bb823766d8df54b53bc07

**Closed** 2015-04-21 12:10 UTC
