### ISSUE TITLE
Irregular behaviour of indication marker

### ISSUE THREAD

**Issue by ShuangjiaoCao** [openETCS/modeling#897] opened 2015-11-06 12:28 UTC
@T12z 

The indication marker has an irregular behaviour. Marker is still visible on within e.g. PIM, TSM... Furthermore the Marker is not exactly on the distance total to the front end of the train.

See figure - marker is visible in PIM but should already disappear in this mode.

![dmi1](https://cloud.githubusercontent.com/assets/7654856/10997055/300923ee-848a-11e5-9532-688779c1c0f0.jpg)
![dmi2](https://cloud.githubusercontent.com/assets/7654856/10997054/30084c12-848a-11e5-8503-fc8ddd42e974.jpg)

**Comment by T12z** [comment] 2015-11-06 13:15
I have not yet confirmed, and wont be able today. Please hang on a little.
Anyways, from my understanding the Indication marker is the transition from PIM to TSM, so it may still be there in PIM. And yes, currently it is *not* made invalid (-1) when passed. So, when do you want me to set it to invalid:
* when the IndicationPoint is passed -- that is, when entering TSM
* or when entering PIM?

And, can you please rephrase "on the distance total to the front end" - it's not clear to me :confused:

**Comment by ShuangjiaoCao** [comment] 2015-11-06 14:00
The Indication marker position would be invalid when entering PIM. 

The location is also not correct.
e.g. If i reduce the speed, the marker position increases again, i think it would not be right?

**Comment by T12z** [comment] 2015-11-06 14:13
I just had a brief call with Baliseyos , and I think we finally reached the crossing of our judgement of this problem (that we have seen since the beginning of the year). 
Now that is a beautiful point for vacation, have a good one @BaseliyosJacob

**Comment by BaseliyosJacob** [comment] 2015-11-06 21:06
Hello @T12z ,

thanks for the wishes.

Comming back to your statement:

I have not yet confirmed, and wont be able today. Please hang on a little.
Anyways, from my understanding the Indication marker is the transition from PIM to TSM, so it may still be there in PIM. And yes, currently it is not made invalid (-1) when passed. So, when do you want me to set it to invalid:

The indication marker is the transition from CSM to PIM or TSM - that means transition to TSM if there is no PIM phase. In this the indication maker will be not visible in PIM or even in TSM phase.

Hope this clarification could help you.

Thank you very much

**Comment by T12z** [comment] 2015-11-09 20:20
Update,
the indication marker being dependent on speed was a typo, fixed, not yet pushed. Also, the value will be -1 ("undefinedSpeed", there is no undefinedDistance) in modes other than CSM or if no target is restricting.

For the speed limits, I did read "my" chapter of the SRS (3.13) forth and back, but there is nada, *nothing* that justifies the proposed modification to make V_permitted **not** being dependent on V_est. (the impact is mostly due to brake-buildup-time) There is one point, that requests V_permitted not to increase, when brake feedback is active. Feedback is not even implemented and yet another factor. While I agree, that the current behavior may be confusing, I am having a hard time inventing something without the spec backing it up. (e.g. when is the limiting reset correctly?)

I hope I can provide a solution along the lines of tomorrow, without breaking too much.

**Comment by T12z** [comment] 2015-11-10 12:51
solution has been provided. Does this look more like the "regular" behaviour?

**Comment by ShuangjiaoCao** [comment] 2015-11-12 15:27
yes, I have tested, it looks like a regular behaviour now:)

**Comment by stefan-karg** [comment] 2015-11-12 16:38
In the current version, I just saw the behaviour, that the Indication marker does already disappear before the TSM mode. According to the DMI specification, this behaviour seems wrong to me.

**Comment by T12z** [comment] 2015-11-12 16:57
Yes, that would also be my understanding.
But from the above comments, I feel told, the marker should vanish when entering PIM *or* TSM, @ShuangjiaoCao said, it shall not be visible in PIM. 

There is a PreindicationLocation (CSM->PIM) and an IndicationLocation (PIM->TSM). If we hop from a TSM->TSM of another target, there is no IndicationMarker, as it is not visible in TSM at all. The Indicator should sit on the IndicationLocation, but I have no idea, *when* it is visible on the DMI, that was the related question.
I am happy either way, as I mentioned before, I am just no DMI expert :wink: 
> So, when do you want me to set it to invalid:
> * [ ] when the IndicationPoint is passed -- that is, when entering TSM
> * [ ] or when entering PIM?

**Comment by stefan-karg** [comment] 2015-11-16 09:25
We will check the correction and close the issue if it's according to our interpretation of the specification.

**Comment by T12z** [comment] 2015-11-18 11:27
since there was no further comment on this by DMI folks, I have reverted to interpretation by Stefan/me that the Marker shall be shown until it is passed. (That is when switching from PIM to TSM by definition). Considering Stefan's last comment, I will hand over responsibility.

**Comment by BaseliyosJacob** [comment] 2015-11-20 08:22
Hello @T12z , the Marker should shown until the Train passed the CSM -> PSM and in the Case there is no PSM it should shown until the Train is passed the CSM -> TSM. In the Case of CSM -> CSM there is no Marker shown. Greetings

**Comment by T12z** [comment] 2015-11-20 16:36
Howdy Baseliyos,
thanks heaps for your input. Can you please quote the reference, so we can agree on this? (Then I  can re-fix next week)

**Comment by BaseliyosJacob** [comment] 2015-11-23 08:30
Hello @T12z ,

maybe this refernce helps you:

Document: ERA_ERTMS_015560

Version: 3.4.0

8.3.8 Indication Marker
8.3.8.1 This DMI object displays in D7 the location where the TSM of the current target starts.
8.3.8.2 The indication marker shall be a horizontal line in yellow with a 2 cells width and a
length equal to the width of D7.
8.3.8.3 The bottom of the indication marker shall be at the location where the TSM related to
the current target starts i.e. at the location where the braking to target indication
supervision limit intersects the MRSP (see Figure 11).

**Comment by BaseliyosJacob** [comment] 2015-11-23 08:32
![image](https://cloud.githubusercontent.com/assets/3975810/11332324/1c867d7e-91c5-11e5-90d7-34c10fae1da7.png)

**Comment by BaseliyosJacob** [comment] 2015-11-23 08:38
There are just this brief information on the DMI spec document. But according to the implementation from ETCS project e.g. ICE 3, i can tell you that the marker is visible until the train passed

- CSM -> PSM margin

- in the case there is no PSM phase: CSM ->TSM margin

Otherwise the marker does not make any sense for the driver. 
- The driver needs the marker to understand that a "interaction" point is either foreseen or the train already in the "interaction" pahse. 

Therefore for the Case where no PSM or TSM will be triggered e.g. CSM->CSM a marker will be not visible.

I hope i could help you to get a little bit more clarfication since the spec is really very rare.

Greetings 

Baseliyos

**Comment by T12z** [comment] 2015-11-23 16:55
sorry mate :wink: 
there is still *nothing* to back up that *opinion* or interpretation of the ICE3-implementation, to switch off the IndicationMarker in PreIndicationMode
(I am cool with all the other cases, other than PIM)
And actually, the transition from CSM to TSM always has a PIM, unless there is an update of information or a really awkward data combination. But SDM would do the right thing in that case.

**Comment by ShuangjiaoCao** [comment] 2015-11-27 09:41
I have set it invisible when entering PreIndicationMode in DMI Controller

**Comment by T12z** [comment] 2015-12-01 10:30
I am still not convinced this is the Right Way:tm: but essentially the bug is fixed, I'll close the issue

**Closed by T12z** 2015-12-01 10:30 UTC
Labels: bug, Sprint-Backlog
