### ISSUE TITLE
[clarification] Timer Management

### ISSUE THREAD

**Issue by T12z** [openETCS/modeling#117] opened 2015-02-12 15:00 UTC
(As discussed in WP3 / Group 1 meeting, 12.02.2015)

Who takes care of the timer management? @JakobGartner 

This is a general question, though obeying timers may be optional after all (SRS Subset 26 / chapter 7)

**Comment by UweSteinkeFromSiemens** [comment] 2015-02-13 09:11
The system time (starting with 0 at system start) is available for any function for the implementation of delays. Additionally, external input events are time-stamped.

**Comment by BenjaminBeichler** [comment] 2015-02-13 15:18
The problem is not how to do it, but who is responsible for it. The SRS
does not assign the task to the Speed and Distance Monitoring. Therefore we
need clarification.

We discussed in the group, that a timer expiration will lead to a change of
the MA and it would be transparent to SaDM. So the timer management is
maybe done outside. If the architect says, we are responsible then we could
do it.

**Comment by JakobGartner** [comment] 2015-02-13 17:21
In my understanding there are aspects of timers that indeed change the location- based profiles.
Especially in the context of MA, there are aspects that I have not yet fully analysed that give me the feeling that there is also action for the train supervision people. 

I will think about an architectural proposal

**Comment by BenjaminBeichler** [comment] 2015-05-07 08:03
As decided in Stuttgart, we set the responsibility for the timer management to the track atlas modules. 

Mainly we identified the need for management of Movement Authority timers, which then are passed without timing infomation to the speed and distance monitoring

@vgontier Do we have already a document about the meaning of all timers ? I know we already talked about, but I don't remember everything

@JakobGartner after a first analysis we could plan our working effort

**Comment by vgontier** [comment] 2015-05-11 07:46
We have analyzed the timers for the breaking curves (see FT.1.5 of the CORE Model), not for the MA. Are you sure MA timers are useful for our model at this step ?

**Comment by BenjaminBeichler** [comment] 2015-05-11 08:53
As far as I understand, FT 1.5 describes the brake build up times, which are directly based on train data and the times are directly used in the calculation of the braking targets (FT 1.6).

I don't know, whether the current usecases need timers. For me it is not easy to say from the abstract description of use cases, but maybe we could leave them out. It was only a concern from my side about responsibilities. Maybe @BaseliyosJacob could say something about the need of timers in MA.

However the chapter 13. does not really deal with timers, but it seems to be needed, or at least we already discussed about the timers of the MA.

**Comment by JakobGartner** [comment] 2015-06-07 08:16
I think we have a decision on this, so I close it. You may reopen if you disagree

**Closed by JakobGartner** 2015-06-07 08:16 UTC
Labels: question
