### ISSUE TITLE
Manage_TrackSideInformation_Integration provides Balises with empty BG header (due to filter)

### ISSUE THREAD

**Issue by janWelte** [openETCS/modeling#491] opened 2015-06-25 12:18 UTC
The run of the first test Model for the Balise Input Channel Validation https://github.com/openETCS/validation/issues/261 showed following failures:

 1. Model provided BG with empty Headers (probably due to filter)
 2. Balises with 8 Balises was not prsented (probably due to wrong consistency check in Modul CheckBGConsistency_Pkg::SubFunction::CompletenessFirstCheck/

Results can be checked by running the test model at https://github.com/openETCS/validation/tree/master/VnVUserStories/VnVUserStoryTUBS/05-Work/CheckBGInt
Test Configuration:
  TestStory = 4
  TestDriver = 2

(Comment: TestStory 4 - BB with single Balise at 100 and BG with 8 Balises at 200)

**Comment by BerndHekele** [comment] 2015-06-26 16:17
Dear Jan,
I will analyse this report  soon.
One remark: could you please add to the project a configuration which already has appropriate settings for the simulation (something like SimuVV).

kr
Bernd

**Comment by BerndHekele** [comment] 2015-06-30 10:55
Dear Jan,

I just opened the model.
I see a change in the test-track which is not reflected by the model.
The Teststory 4 AmsterdamUtrechtTrack1 does no longer exist.

I replaced this operator with a new one for balises.
Can you please "push" this correction to the master.

A first analysis confirms your result: 
I see an error in the MessageBuffer model of the InformationFilter.
I will ask Alexander for further analysis.

kr
Bernd

**Comment by BerndHekele** [comment] 2015-06-30 12:38
The error has been corrected in the TrackSide Integration model.
For the correction a new output to calculate train position is needed.
This part of the change is not included in the current solution.

@UweSteinkeFromSiemens

**Comment by BerndHekele** [comment] 2015-07-07 12:45
We (Uwe and me) had a short talk on the issue. To summarize the result:
The Information Filter needs extra cycles for sending information. 
To get the cycles a "ready" signal is to be taken in use (see Uwe's guide). 
Input to the evc system is only feasable when ready = true.

This results into the following corrective actions:
ElementFilter: generate Ready output when buffer is empty
TrackSide Model: pass this signal to the EVC.
Calculate Train Position needs an extra input with the output of the BG VD model.
EVC: combine the different ready signals to an EVC is ready.
TestBench: react on signal. Stop input when not ready.

Any comments?
@stefan-karg @astante @UweSteinkeFromSiemens

**Comment by janWelte** [comment] 2015-07-07 14:23
I'll have a look at this solution and see whether I can follow every change.

Am I right, that this is unrelated to the second part
"2. Balises with 8 Balises was not prsented (probably due to wrong consistency check in Modul CheckBGConsistency_Pkg::SubFunction::CompletenessFirstCheck/" which still was an issue yesterday.

**Comment by stefan-karg** [comment] 2015-07-07 19:00
@BerndHekele @UweSteinkeFromSiemens 

As discussed in todays telephone conference, I separated the issue "Modify clocking strategy" from the EVC environment issue. The clocking issues described here are the same as described in the new issue (#535) and the integration of the concept can be done in one step from my point of view. I will also provide the necessary modifications in the environment model when the modifications are done in the EVC model.

I would suggest to first collect all the models in issue #535, which use the ready-flag concept in order to get an overview over the necessary modifications.

**Comment by BerndHekele** [comment] 2015-07-08 07:09
Regarding Jan's question: yes - this is a seperate problem.
I did not check this part yet.

**Comment by UweSteinkeFromSiemens** [comment] 2015-07-08 07:12
Dear Bernd,
we stated that calculateTrainPosition may receive delayed linking information originating from balises. This is caused by the informationFilter buffering balise datagrams and feeding them into the input data stream later on. Is it this, what you meant with "Calculate Train Position needs an extra input with the output of the BG VD model."?

**Comment by BerndHekele** [comment] 2015-07-08 16:26
Hi Uwe,
yes - the additional port is reasened by the buffering of information. Information comming from the Information Filter can be delayed. 
Therefore, we need a second output to your function.

This problem is not really relevant for the Utrech-Amsterdam scenarios. Let's take some time to analyse a proper solution for the output flow of the information filter in buffering scenarios.

Jan,
if you agree we postpone this correction to the next iteration?

**Comment by UweSteinkeFromSiemens** [comment] 2015-07-09 09:26
I don't agree with a second output to calculateTrainPosition, because the track messages from the API and the stored messages from the infomationFilter have to be merged into outMessage / msgFromTrack in the correct order before, with "source" indicating it as a delayed balise datagram, as we stated yesterday,

A second output instead would displace a locally solvable task of Manage_TrackSideInformation_Integration / InformationFilter to a subsequent stage, which in general should be avoided as an architectural principle.

**Comment by JakobGartner** [comment] 2015-07-09 12:33
I tend to agree with Uwe:

The information flow that comes from the trackside input processing module must be consistent and complete.

The filter (which may be more than just what it is now, I don’t know) must be intelligent enough to make sure that what comes out in the end is a flow of consistent messages that are self- contained.


If then there is a flag “delayed” or if the following modules are robust enough to process delayed telegrams just based on their timestamp is yet another design decision which has nothing to do with the processing of the trackside info itself.

**Comment by janWelte** [comment] 2015-07-09 14:23
How do we document this discussion. If to agree with Uwe and Jakob as I see a valid flag in the data as sufficient indicator. The function has to be stable enough to process things with delays in time.

As the original bug for this issue, has been fixed I would like to close this one and shift the open points to better places.

**Comment by BerndHekele** [comment] 2015-07-09 15:00
Just as a reminder: delaying messages at this point is not by bad design but by SRS (section 4.8). Lets descuss an example:

we run in Level 2

BG1 has linking information
Calculate train position needs to adjust the position - therefore BG-Header has to be passed to CTP
Linking information has to be delayed for a level change to level 1.

Option 1 (information is delayed)  
 - means CTP cannot correct the position.  So nogo

Option 2 (BG-Position is passed without delay  and Linking packages with the delay, message is marked as delayed) - this would look unclean cause different messages are output at the same time.
But, the quality of the parameters is different. One is used to adjust the position and nothing else,  and the other is used to pass the packets.

Therefore,   
Option 3 (Sequentialise the information)
I believe this is Uwe's  original Idea with the use of the ready flag  I did not summarize correctly.
 - first cycle BG-Information is sent without extra packets  
- when the delayed message is valid this information is sequemced. In order to make sure the BG-information is not to be used the message has to be marked. Otherwise there is a risk for wrong calculations.

Uwe, is this according to the discussion we had at the phone?  
Jakob, can we (you Uwe and myselves) have a short argument (phone) on the ready flag. I don't like to have this as an open issue since it seems to be a straight forward concept.

**Comment by janWelte** [comment] 2015-07-09 15:15
we have to seperate here between delayed processing and intentionaly delayed context of balise messages due to level or mode changes. Here has to be separated between BGs (Header) and Information. I think a short discussion between all of you should find a good way to go on.

**Comment by UweSteinkeFromSiemens** [comment] 2015-07-13 07:41
For clarification, as I understand the problem: 
- The train passes a linked balisegroup comprising linking information (packet 5)
- calculateTrainPosition needs to know about the passage for position adjustment immediately.
- If the linking information (packet 5) received from the same BG has to be taken into account, depends on the current level. The decision is made by the informationFilter function, which stores the linking information for a probably later switch to level 1. 
- This is why the linking information must not be applied to calculateTrainPosition, as long as it must not be used.
- Later, with a change to Level 1, the informationFilter may forward the linking information to calculateTrainPosition without making believe, that the originating BG has just now been passed.
- The delayed feed in of the linking information from a BG is similar as if it has been received via radio, which will happen with a delay after passing the LRBG anyway.

So, calculateTrainPosition needs to know, that it receives a delayed linking information from a BG in contrast to receiving it with the passage event itself.

Please don't mix this with the concept of a "ready" flag: The ready flag may be used to give the informationFilter the freedom to feed internal stored datagrams into the "normal" data flow without conflict with events from outside.

**Comment by BerndHekele** [comment] 2015-12-01 10:47
Correction Available.

**Closed by BerndHekele** 2015-12-01 10:47 UTC
Labels: bug, User Story 4
