### ISSUE TITLE
BG with inconsitent telegram headers is build as BG with flag "valid=true"

### ISSUE THREAD

**Issue by janWelte** [openETCS/modeling#354] opened 2015-05-12 16:54 UTC
Testcase: 
BG with 4 Balises (3rd header gives ntotal=3 Balises in BG) is passed by OBU

Incorrect behaviour:
Manage_TrackSideInformation_Integration gives out massege, although n_total in one telegram does not fit.

Comment:
sss-script will be provided to run case

**Comment by JakobGartner** [comment] 2015-05-12 18:28
out of US scope

**Comment by MarcBehrens** [comment] 2015-05-12 18:50
@jacobgartner can you please point to the specific use case ruling out this constellation?
Currently we are modelling all the use cases and did not find this restriction?

Maybe you mean that this is outside of the demonstration track Amsterdam Utrecht. There you are right.

**Comment by JakobGartner** [comment] 2015-05-12 18:51
the max number of balises in a BG on Amsterdam- Utrecht is 2

all our US relate to this track.

**Comment by MarcBehrens** [comment] 2015-05-12 19:07
@basleliyosjacob can you please clarify:

As a product owner do you want to have the scope of the OBU reduced to support up to two balises?

**Comment by BerndHekele** [comment] 2015-05-13 06:59
I see this issue as valuable and we will analyse aqnd correct the behaviour if it is in the EVC.
In verification we should not limit on the Utrecht Amsterdam Use-cases if the function can be provided as a part of the model.

**Comment by Farhangi** [comment] 2015-05-13 08:22
Hello @janWelte , I will analyze the case as soon as I get sss-script.
I can imagine that 3rd telegram from "Receive_TrackSide_Msg" is filtered, and 2nd or 4th telegram is a duplicate of 3rd telegram.

**Comment by janWelte** [comment] 2015-05-19 16:16
@Farhangi 
You can find the [Consistency test sss-file] (https://github.com/openETCS/validation/tree/master/VnVUserStories/VnVUserStoryTUBS/05-Work/Scenarios/SSS-Files) (commit 553c7d48121afa414220ec1a9a67d92c824150c3) showing a case like this for a BG with 2 Balises. This sss.file is set to be run on Manage_TrackSideInformation_Integration.etp.

In this case 3 BGs are passed by the train (InitialVelocity 5.0 in testgenerator)
1. BG with 8 balises, no duplicates (consistent)
2. BG with 2 balises, no duplicates (inconsistent)
3. BG with 2 balises, duplicates (consistent)

Out message is given for all 3 BGs with valid = true. (2. BG should be flagged as inconsistent)

**Closed** 2015-06-01 06:15 UTC
Labels: bug
