### ISSUE TITLE
Testbench Integration project is corrupted

### ISSUE THREAD

**Issue by janWelte** [openETCS/modeling#802] opened 2015-10-12 12:13 UTC
As I wanted to try the track corrections I found that the test bench project is inconsistent due to file name changes. (I guess this is not part of the current model changes). Please correct this problem.

![image](https://cloud.githubusercontent.com/assets/2719967/10427643/82641660-70eb-11e5-9c44-ef04cb67ba3b.png)

**Comment by stefan-karg** [comment] 2015-10-12 15:57
Dear Jan,

I fixed the problem in commit 75fc19eb51728dcaef4b5dfdd31198c86130f8be. I forgot to commit a .xscade-file after moving the integration operators to a separate package.

**Comment by UweSteinkeFromSiemens** [comment] 2015-10-13 07:41
The current model is still broken, due to several type inconsisties.

**Comment by stefan-karg** [comment] 2015-10-13 08:12
Since the data types are adjusted at the moment, the Testbench will remain in a broken state until these type inconsistencies are resolved in all models. 

The necessary corrections in the Toolbox and the Testbench are performed already, see commit baaabd7a9ebc0d29037ac65b3c5d816d573f1eac and 687861129aa174cb1d508455c8a28ba377bf4d7f.

**Comment by stefan-karg** [comment] 2015-11-06 07:51
Problem described in the issue is solved

**Closed by stefan-karg** 2015-11-06 07:51 UTC
Labels: bug in Integration
