### ISSUE TITLE
InformationFilter: Output message stays valid for 2 clocks

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#433] opened 2015-06-08 11:04 UTC
While running TestBenchExample: ManageTrackSideInformation_Integration: InformationFilter with 
- acceleration = 100.0 and
- initialPosition = 5400.0
ManageTrackSideInformation_Integration.outputMessage.valid stays true for 2 subsequent clocks (clock no. 1038 and 1039). Must be true for only 1 clock cycle. 
This seems to be caused by the InformationFilter function.

**Comment by BerndHekele** [comment] 2015-06-08 11:15
When trying to reproduce the test I get an modelling error from track-messages. 
Do you have a different state?

cu
Bernd
@JakobGartner

**Comment by JakobGartner** [comment] 2015-06-08 11:20
This is the status on Github—

**Comment by BerndHekele** [comment] 2015-06-08 11:50
weird - I get the error in your model from a fresh clone.

**Comment by JakobGartner** [comment] 2015-06-08 11:51
you get what kind of error?

**Comment by BerndHekele** [comment] 2015-06-08 11:54
![image](https://cloud.githubusercontent.com/assets/3288918/8034205/d2a34b8c-0de5-11e5-9263-da141a10cf1e.png)

**Comment by UweSteinkeFromSiemens** [comment] 2015-06-08 11:59
Yes, this is why this function from TM has been changed. I will push a corrected version of calculateTrainPosition in a few minutes, that fixes the broken model.

**Comment by BerndHekele** [comment] 2015-06-08 12:02
uff.
I thought I'm crazy.

**Comment by astante** [comment] 2015-06-16 14:36
The problem shoud be fixed in 6203870896f084cc3733f4bf21a229afc8e8e4e3. However I am not able to test it with the TestBenchExample due to errors in it.

**Comment by BerndHekele** [comment] 2015-06-18 08:59
I close this as a duplicate.
Correction is available.
Verification of the solution is "controled" with the duplicate.

**Closed by BerndHekele** 2015-06-18 08:59 UTC
Labels: bug, Information Filter
