### ISSUE TITLE
State of Issue tracker / asking for model-after-review-plan

### ISSUE THREAD

**Issue by T12z** [openETCS/modeling#912] opened 2015-11-13 10:45 UTC
Dear WP3 folks,

as of 13.Nov. the issue tracker contains ~300 issues. 100 of them even w/o assignees. Quite a few have lost attention and get stale / not relevant anymore.

Is there any plan, if there will be any 
* sanitizing of the issue tracker?
* concentrate of known bugs / limitation of the model?
* "penalty" on open issues?

Other than the deliverables to ITEA, will there be some real, non-sprint release?
I know, you try to strive for as much functionality as possible, which is great, but this may end up in a mess that is not maintainable in a few months time. :weary: 

PS I assigned Peter as the product owner, hoping, that is correct.

**Comment by mahlmann** [comment] 2015-11-16 08:45
Dear Thorsten, dear WP3 team @openETCS/modeling ,

I think there are several  reasons for this. One of these reasons is that not all of us devote the necessary attention to the issues they have been assigned to, unfortnately.

I think the WP3 lead is in charge here. However, in the end we can only solve this by acting together. 

My proposal would be that each of us takes a look at the issues he or she did open (this can be filtered easily) and then
 - close the issue, if it is no more relvant,
 - or ask the person assigned about the status if the issue is still relevant and no actions have been taken.

**Comment by T12z** [comment] 2015-11-16 11:43
Thanks for your reply,
though I am actually quite realistic, the asked for discipline will be limited, as seen in last months (I am not about blaming anybody)
But I am afraid we need some sort of dedicated wrap-up before people/commiters are pulled to other projects by the new year.

**Closed** 2015-12-10 16:43 UTC
Labels: bug in Integration
