### ISSUE TITLE
Inconsistencies in AmsterdamUtrechtL2::AmsterdamUtrechtTrack1 Balise header

### ISSUE THREAD

**Issue by janWelte** [openETCS/modeling#544] opened 2015-07-09 17:36 UTC
As asked by Baseliyos in #495 I've verified the Balise header as I've build a first test model to check communication in US-4.

By running the full track and comparing the recognized BGs by the OBU and my BTMtest model I've been able to check whether all balises are correctly received.

Overall this has been quite successful, but the following 8 BGs have shown inconsistencies. In most cases these are related to implementation bugs, as wrong headers have been plugged in balises.

1. BG352 is not recognized when the train starts at position 0.0 (probably a conversion problem, more details are needed)

2. BG357 wrong header as BG367

3. BG374 problem with positon conversion

4. BG376 wrong Balise header in 376_0 (BG375_header_B0)

5. BG382 wrong header in Balise_382_0 (BG382_headerB1) in both same header

6. BG391 wrong header as BG371

7. BG396 wrong header as BG139

8. BG412 wrong header BG411

This check has only verified the BG header. Packet Data will be verified in future versions.

**Comment by JakobGartner** [comment] 2015-07-09 17:43
Hello Jan ,

Thanks for your work .

Can you please assign to @mairamou?

I will check for the apparent conversion errors in parallel



On 9 juil. 2015, at 14:36, Jan Welte <notifications@github.com> wrote:

As asked by Baseliyos in #495
<https://github.com/openETCS/modeling/issues/495> I've verified the Balise
header as I've build a first test model to check communication in US-4.

By running the full track and comparing the recognized BGs by the OBU and
my BTMtest model I've been able to check whether all balises are correctly
received.

Overall this has been quite successful, but the following 8 BGs have shown
inconsistencies. In most cases these are related to implementation bugs, as
wrong headers have been plugged in balises.

   1.

   BG352 is not recognized when the train starts at position 0.0 (probably
   a conversion problem, more details are needed)
   2.

   BG357 wrong header as BG367
   3.

   BG374 problem with positon conversion
   4.

   BG376 wrong Balise header in 376_0 (BG375_header_B0)
   5.

   BG382 wrong header in Balise_382_0 (BG382_headerB1) in both same header
   6.

   BG391 wrong header as BG371
   7.

   BG396 wrong header as BG139
   8.

   BG412 wrong header BG411

This check has only verified the BG header. Packet Data will be verified in
future versions.

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/544>.

**Comment by JakobGartner** [comment] 2015-07-09 18:16
Hello Jan

Can you precise "position conversion problem" so that we can reproduce ?

Thanks


Jakob



On 9 juil. 2015, at 14:36, Jan Welte <notifications@github.com> wrote:

As asked by Baseliyos in #495
<https://github.com/openETCS/modeling/issues/495> I've verified the Balise
header as I've build a first test model to check communication in US-4.

By running the full track and comparing the recognized BGs by the OBU and
my BTMtest model I've been able to check whether all balises are correctly
received.

Overall this has been quite successful, but the following 8 BGs have shown
inconsistencies. In most cases these are related to implementation bugs, as
wrong headers have been plugged in balises.

   1.

   BG352 is not recognized when the train starts at position 0.0 (probably
   a conversion problem, more details are needed)
   2.

   BG357 wrong header as BG367
   3.

   BG374 problem with positon conversion
   4.

   BG376 wrong Balise header in 376_0 (BG375_header_B0)
   5.

   BG382 wrong header in Balise_382_0 (BG382_headerB1) in both same header
   6.

   BG391 wrong header as BG371
   7.

   BG396 wrong header as BG139
   8.

   BG412 wrong header BG411

This check has only verified the BG header. Packet Data will be verified in
future versions.

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/544>.

**Comment by JakobGartner** [comment] 2015-07-09 19:24
Mairamou and I have discussed your issues.
We can reproduce all but no.3

She has provided a correction but can't send due to power failure in her
neighborhood . She will commit tomorrow morning .

First comments embedded in your numbered items

On 9 juil. 2015, at 14:36, Jan Welte <notifications@github.com> wrote:

As asked by Baseliyos in #495
<https://github.com/openETCS/modeling/issues/495> I've verified the Balise
header as I've build a first test model to check communication in US-4.

By running the full track and comparing the recognized BGs by the OBU and
my BTMtest model I've been able to check whether all balises are correctly
received.

Overall this has been quite successful, but the following 8 BGs have shown
inconsistencies. In most cases these are related to implementation bugs, as
wrong headers have been plugged in balises.

   1.

   BG352 is not recognized when the train starts at position 0.0 (probably
   a conversion problem, more details are needed)

Corrected. This was a typo in the position information of BG352


   1.

   BG357 wrong header as BG367

Corrected


   1.

   BG374 problem with positon conversion

We can't reproduce .
The engineering data, the track plan Abcoude sheet 8A and the engineering
data in the model all have the value  7857.


   1.

   BG376 wrong Balise header in 376_0 (BG375_header_B0)

Corrected


   1.

   BG382 wrong header in Balise_382_0 (BG382_headerB1) in both same header

Corrected


   1.

   BG391 wrong header as BG371

Corrected


   1.

   BG396 wrong header as BG139

Corrected


   1.

   BG412 wrong header BG411

Corrected



This check has only verified the BG header. Packet Data will be verified in
future versions.

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/544>.

**Comment by janWelte** [comment] 2015-07-09 19:30
Thank You.

I've to check 3. closer myself as it has only been clear from my test that this was not send to the BTM.

I have not ha the option to check it in depth already but I'll do this as I'll enhance my test model.

Overall thanks for the great work.

Jan Welte



Am 09.07.2015 um 21:24 schrieb Jakob Gärtner <notifications@github.com<mailto:notifications@github.com>>:

Mairamou and I have discussed your issues.
We can reproduce all but no.3

She has provided a correction but can't send due to power failure in her
neighborhood . She will commit tomorrow morning .

First comments embedded in your numbered items

On 9 juil. 2015, at 14:36, Jan Welte <notifications@github.com<mailto:notifications@github.com>> wrote:

As asked by Baseliyos in #495
<https://github.com/openETCS/modeling/issues/495> I've verified the Balise
header as I've build a first test model to check communication in US-4.

By running the full track and comparing the recognized BGs by the OBU and
my BTMtest model I've been able to check whether all balises are correctly
received.

Overall this has been quite successful, but the following 8 BGs have shown
inconsistencies. In most cases these are related to implementation bugs, as
wrong headers have been plugged in balises.

1.

BG352 is not recognized when the train starts at position 0.0 (probably
a conversion problem, more details are needed)

Corrected. This was a typo in the position information of BG352


1.

BG357 wrong header as BG367

Corrected


1.

BG374 problem with positon conversion

We can't reproduce .
The engineering data, the track plan Abcoude sheet 8A and the engineering
data in the model all have the value 7857.


1.

BG376 wrong Balise header in 376_0 (BG375_header_B0)

Corrected


1.

BG382 wrong header in Balise_382_0 (BG382_headerB1) in both same header

Corrected


1.

BG391 wrong header as BG371

Corrected


1.

BG396 wrong header as BG139

Corrected


1.

BG412 wrong header BG411

Corrected



This check has only verified the BG header. Packet Data will be verified in
future versions.

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/544>.

**Comment by mairamou** [comment] 2015-07-10 10:43
As Jakob has already described, the issues are fixed with the exception of point (3) where I need to understand the problem better

**Comment by JakobGartner** [comment] 2015-07-27 23:58
@janWelte 
can you please check what is wrong with BG374?
Please note that many balises have been repositioned in order to build a self-consistent track.

**Comment by BerndHekele** [comment] 2015-12-01 10:45
Track works.
Can be closed.

**Closed by BerndHekele** 2015-12-01 10:45 UTC
Labels: bug, User Story 4
