### ISSUE TITLE
modeling/model/Scade/System/ObuFunctions/TrackAtlasAndMRSP_Types

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#99] opened 2015-02-02 17:36 UTC
First definition of types to interface to Train Supervision module (MRSP and Gradient Profile)

Please comment/ sync

**Comment by christianstahl** [comment] 2015-02-02 21:02
Ich kehre zurück am 09.02.2015.

I am out of office until February 9th, 2015.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "[modeling] modeling/model/Scade/System/ObuFunctions/TrackAtlasAndMRSP_Types (#99)" gesendet am 02.02.2015 18:36:25. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.=

**Comment by JakobGartner** [comment] 2015-02-03 12:52
Alternatives for profile sections (gradient profile sections, MRSP sections, MA sections)

1) Flag in last section ( " I am last" )
2) Variable indicating the number of total sections (per category)
3) both

Any preference?

**Comment by VNuhaan** [comment] 2015-02-03 13:02
If you do the first, then you can easily make a circular buffer.

Vincent

Van: Jakob Gärtner [mailto:notifications@github.com]
Verzonden: dinsdag 3 februari 2015 13:52
Aan: openETCS/modeling
Onderwerp: Re: [modeling] modeling/model/Scade/System/ObuFunctions/TrackAtlasAndMRSP_Types (#99)


Alternatives for profile sections (gradient profile sections, MRSP sections, MA sections)

1) Flag in last section ( " I am last" )
2) Variable indicating the number of total sections (per category)
3) both

Any preference?

—
Reply to this email directly or view it on GitHub<https://github.com/openETCS/modeling/issues/99#issuecomment-72645100>.

________________________________
Lloyd’s Register is a trading name of Lloyd’s Register Group Limited and its subsidiaries. For further details please see http://www.lr.org/entities © Lloyd's Register Group Limited 2012

Lloyd's Register Group Limited, its affiliates and subsidiaries and their respective officers, employees or agents are, individually and collectively, referred to in this clause as 'Lloyd's Register'. Lloyd's Register assumes no responsibility and shall not be liable to any person for any loss, damage or expense caused by reliance on the information or advice in this document or howsoever provided, unless that person has signed a contract with the relevant Lloyd's Register entity for the provision of this information or advice and in that case any responsibility or liability is exclusively on the terms and conditions set out in that contract.

**Comment by JakobGartner** [comment] 2015-02-03 13:26
@Vincent, yes that was my initial idea.

If however one wants to read the information in reverse direction, or randomly, then a directly accessible information on the size of the data could be helpful

So it depends on the consumer’s design choices

**Comment by BenjaminBeichler** [comment] 2015-02-03 13:41
I think you mean something like an index to the last element in an array, isn't it ? 

This would be sufficient. I only see a boolean flag relevant in for the map/foldw operators, but there the condition could be easy generated from such an index.

I don't know, whether it's good to create a circular buffer on functional level, but it will be also easy possible with such an index and a mod operation.

**Comment by christianstahl** [comment] 2015-02-03 15:02
Ich kehre zurück am 09.02.2015.

I am out of office until February 9th, 2015.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [modeling] modeling/model/Scade/System/ObuFunctions/TrackAtlasAndMRSP_Types (#99)" gesendet am 03.02.2015 14:02:06. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.=

**Comment by christianstahl** [comment] 2015-02-03 15:02
Ich kehre zurück am 09.02.2015.

I am out of office until February 9th, 2015.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [modeling] modeling/model/Scade/System/ObuFunctions/TrackAtlasAndMRSP_Types (#99)" gesendet am 03.02.2015 13:52:24. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.=

**Comment by christianstahl** [comment] 2015-02-03 15:02
Ich kehre zurück am 09.02.2015.

I am out of office until February 9th, 2015.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [modeling] modeling/model/Scade/System/ObuFunctions/TrackAtlasAndMRSP_Types (#99)" gesendet am 03.02.2015 14:26:43. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.=

**Comment by christianstahl** [comment] 2015-02-03 15:02
Ich kehre zurück am 09.02.2015.

I am out of office until February 9th, 2015.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [modeling] modeling/model/Scade/System/ObuFunctions/TrackAtlasAndMRSP_Types (#99)" gesendet am 03.02.2015 14:41:43. 

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.=

**Comment by BenjaminBeichler** [comment] 2015-02-10 17:59
@JakobGartner 
the committed SCADE Model in Github has still missing types, could you fix this ?

**Comment by JakobGartner** [comment] 2015-02-10 19:04
@BenjaminBeichler, the types have been completed

**Comment by BenjaminBeichler** [comment] 2015-02-24 18:04
@JakobGartner  
could you please change the type to the structure, we discussed in Berlin (delete the length, insert a valid flag, to harmonize with other modules):
MRSP_section{
L_type: Loc_abs
V_type: MRS
bool: valid
}

**Comment by JakobGartner** [comment] 2015-07-01 00:37
this was done since long, can you please close the issue?

**Closed** 2015-07-01 06:57 UTC
